server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: authlog
    static_configs:
      - targets: [localhost]
        labels:
          job: authlog
          host: ${HOSTNAME}
          __path__: /var/log/auth.log
  - job_name: syslog_file
    static_configs:
      - targets: [localhost]
        labels:
          job: syslog
          host: ${HOSTNAME}
          __path__: /var/log/syslog
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    pipeline_stages:
      - docker: {}
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        target_label: 'container'
      - source_labels: ['__meta_docker_container_label_com_docker_compose_service']
        target_label: 'service'
  - job_name: syslog_receiver_udp
    syslog:
      listen_address: 0.0.0.0:1514
      labels:
        job: syslog
      idle_timeout: 60s
      listen_protocol: udp
      use_incoming_timestamp: true
    relabel_configs:
      - source_labels: ['__syslog_message_hostname']
        target_label: host
